trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
# Checkout the code
- task: Checkout@1
  displayName: 'Checkout Code'

# Run C# API Tests
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Run API Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration Release --collect:"Code Coverage"'

- task: PublishTestResults@2
  displayName: 'Publish API Test Results'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults/*.xml'
    failTaskOnFailedTests: true

# Run Playwright UI Tests
- task: UseNode@2
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: npm ci
  displayName: 'Install Playwright Dependencies'
  workingDirectory: frontend_tests/playwright

- script: npx playwright test
  displayName: 'Run Playwright Tests'
  workingDirectory: frontend_tests/playwright

- task: PublishTestResults@2
  displayName: 'Publish Playwright Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    failTaskOnFailedTests: true
